import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
<<<<<<< HEAD
import Footer from "@/components/Footer";
=======
>>>>>>> e0dc322c62330917ba1f03f5464ccd9992454974

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
<<<<<<< HEAD
  title: "SmartMock",
  description: "AI Mock Interview Platform",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> e0dc322c62330917ba1f03f5464ccd9992454974
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
<<<<<<< HEAD
      <html lang="en">
        <body className={`${inter.className} min-h-screen flex flex-col`}>
          {/* The Toaster component is likely for toast notifications */}
          <Toaster />

          {/* Page content goes here */}
          <div className="flex-grow">
            {children}
          </div>

          {/* Footer will always be at the bottom */}
          <Footer />
        </body>
      </html>
=======
    <html lang="en">
      <body className={inter.className}>
      <Toaster />
      {children}</body>
    </html>
>>>>>>> e0dc322c62330917ba1f03f5464ccd9992454974
    </ClerkProvider>
  );
}
